### ISSUE TITLE
free code

### ISSUE THREAD

**Issue by Dukemz** [xAndrei166/duckbot#1]
free code

**Comment by xAndrei166** [comment]
what is this

**Comment by Dukemz** [comment]
dukemz gaming

**Comment by xAndrei166** [comment]
why am I able to reply to this via email

**Comment by Dukemz** [comment]
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:72.0pt 72.0pt 72.0pt 72.0pt;}
div.WordSection1
	{page:WordSection1;}

**Comment by xAndrei166** [comment]
:(

**Comment by Dukemz** [comment]
oh no
our email
its broken

**Comment by xAndrei166** [comment]
Bro what
